### ISSUE TITLE
Cannot run 'multi-templates' and 'simple' examples

### ISSUE THREAD

**Issue by shaal** [basaltinc/knapsack#542]
**Describe the bug**
* examples/multi-templates demo doesn't run.
* examples/simple demo doesn't run.

**To Reproduce**
1. clone repo
1. `yarn`
1. `yarn build`
1. `cd examples/multi-templates` (or `cd examples/simple`)
1. `yarn start`

You'll see the following error:
```
/Users/shaal/code/test/knapsack/knapsack/dist/server/dbs/file-db.js:127
    throw new Error(msg);
    ^

Error: Data validation error for data/knapsack.settings.json
The data:
{
 "title": "Multi Template System",
 "subtitle": "A Simple Example of a Design System",
 "slogan": "Don't repeat yourself",
 "parentBrand": {
  "logo": "",
  "title": "",
  "homepage": ""
 },
 "customSections": [
  {
   "id": "design-tokens",
   "title": "Design Tokens",
   "showInMainMenu": true,
   "pages": [
    {
     "id": "colors",
     "title": "Colors"
    }
   ]
  }
 ]
}

The error:
data should NOT have additional properties
[
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "customSections"
    },
    "message": "should NOT have additional properties"
  }
]
    at Settings.validateConfig (/Users/shaal/code/test/knapsack/knapsack/dist/server/dbs/file-db.js:127:11)
    at Settings.parse (/Users/shaal/code/test/knapsack/knapsack/dist/server/dbs/file-db.js:169:14)
    at Settings.readSync (/Users/shaal/code/test/knapsack/knapsack/dist/server/dbs/file-db.js:190:17)
    at new FileDb2 (/Users/shaal/code/test/knapsack/knapsack/dist/server/dbs/file-db.js:69:25)
    at new Settings (/Users/shaal/code/test/knapsack/knapsack/dist/server/settings.js:38:5)
    at bootstrap (/Users/shaal/code/test/knapsack/knapsack/dist/lib/bootstrap.js:68:20)
    at bootstrapFromConfigFile (/Users/shaal/code/test/knapsack/knapsack/dist/lib/bootstrap.js:112:10)
    at Object.<anonymous> (/Users/shaal/code/test/knapsack/knapsack/dist/cli/knapsack-cli.js:60:56)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
```

**Expected behavior**
Expecting like other demos in `/examples/` folder - that `yarn start` would run a local server that I can view the example in my browser.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Cataline (10.15.5)
 - NodeJS v14.2.0 / v12.14.1

**Additional context**

**Comment by EvanLovely** [comment]
Both of those examples are still from Knapsack v1 & they have not been updated to Knapsack v2. Take a look at `examples/bootstrap` as that one does work with Knapsack v2. Thanks for the clear issue description!
